#!/bin/bash

set -e

ROOT_TASK_DIR=$(pwd)
TIDYBLOB_RC_DIR=$ROOT_TASK_DIR/tidyblob-release-candidate
VERSION=$(cat version/number)

echo "Promoting tidyblob release candidate to final with version: $VERSION"

mv "$TIDYBLOB_RC_DIR"/* "tidyblob-$VERSION.tar.gz"

echo "Built file: tidyblob-$VERSION.tar.gz"
