jobs:
- name: unit
  plan:
  - get: tidyblob
    trigger: true
  - task: unit
    file: tidyblob/ci/unit.yml

- name: build
  serial_groups: [version]
  plan:
    - aggregate:
      - get: tidyblob
        passed: [unit]
        trigger: true
      - get: version
        params: {pre: rc}
    - task: build
      file: tidyblob/ci/build.yml
    - put: tidyblob-final
      params: {from: build/tidyblob.*.tar.gz}

resources:
- name: tidyblob
  type: git
  source:
    uri: git@github.com:teddyking/tidyblob.git
    branch: master
    private_key: {{github-private-key}}

- name: version
  type: semver
  source:
    bucket: tidyblob-pipeline-artifacts
    region_name: eu-west-1
    key: current-version
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: tidyblob-final
  type: s3
  source:
    bucket: tidyblob
    region_name: eu-west-1
    regexp: tidyblob-(.*).tgz
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
